create table DANHMUC
(
    DanhMucId text NOT NULL,
	Ten text NOT NULL,
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT DANHMUC_pkey PRIMARY KEY (DanhMucId)
);

create table USERS
(
    UsernameID text NOT NULL,
    matkhau character varying COLLATE pg_catalog."default" NOT NULL,
	Ten text NOT NULL,
	sokhoahochoanthanh integer,
	gmail text NOT NULL,
	lockuser boolean,
	IsAdmin boolean,
	ImagePath character(100),
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT USERSs_pkey PRIMARY KEY (UsernameID)
);
create table GIAOVIEN
(
    TeacherID text NOT NULL,
	Ten text NOT NULL,
	GioiThieu text,
	ChuyenMon text,
	ImagePath character(100),
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT GIAOVIEN_pkey PRIMARY KEY (TeacherID)
);
create table KHOAHOC
(
    CourseID text NOT NULL,
	Ten text NOT NULL,
	Gia decimal,
	TongQuan text,
	ChiTiet integer,
	ImagePath character(100),
	TeacherID text,
	DanhMucID text,
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone ,
    deleted_at timestamp without time zone,
    CONSTRAINT KHOAHOC_pkey PRIMARY KEY (CourseID)
);
create table BAIHOC
(
    SessionID text NOT NULL,
	Chuong integer,
	NoiDung text,
	Link text,
	CourseID text,
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT BAIHOC_pkey PRIMARY KEY (SessionID)
);
create table COURSEOFUSER
(
    COUID text NOT NULL,
	HoanThanh integer,
	CourseID text,
	UsernameID text,
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT COURSEOFUSER_pkey PRIMARY KEY (COUID)
);
create table DONHANG
(
    DonHangID text NOT NULL,
	TongTien decimal,
	LoaiHinhTT text,
	NgayMua timestamp,
	UsernameID text,
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT DONHANG_pkey PRIMARY KEY (DonHangID)
);
create table CTDONHANG
(
    CTDHID text NOT NULL,
	DonHangID text,
	Tien decimal,
	CourseID text,
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT CTDONHANG_pkey PRIMARY KEY (CTDHID,DonHangID)
);
create table DANHGIA
(
    DANHGIAID text NOT NULL,
	Comment text,
	Rate int,
	date_dg timestamp,
	UsernameID text,
	CourseID text,
    created_at timestamp without time zone DEFAULT NOW(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT DANHGIA_pkey PRIMARY KEY (DANHGIAID)
);

ALTER TABLE khoahoc
ADD CONSTRAINT fk_kh_dm FOREIGN KEY (danhmucid) REFERENCES danhmuc (danhmucid);
ALTER TABLE khoahoc
ADD CONSTRAINT fk_kh_gv FOREIGN KEY (teacherID) REFERENCES giaovien (teacherID);

ALTER TABLE courseofuser
ADD CONSTRAINT fk_cou_u FOREIGN KEY (UsernameID) REFERENCES USERS (UsernameID);
ALTER TABLE courseofuser
ADD CONSTRAINT fk_cou_kh FOREIGN KEY (CourseID) REFERENCES KHOAHOC (CourseID);

ALTER TABLE danhgia
ADD CONSTRAINT fk_dg_u FOREIGN KEY (UsernameID) REFERENCES USERS (UsernameID);
ALTER TABLE danhgia
ADD CONSTRAINT fk_dg_kh FOREIGN KEY (CourseID) REFERENCES KHOAHOC (CourseID);

ALTER TABLE donhang
ADD CONSTRAINT fk_dh_u FOREIGN KEY (UsernameID) REFERENCES USERS (UsernameID);

ALTER TABLE ctdonhang
ADD CONSTRAINT fk_ct_kh FOREIGN KEY (CourseID) REFERENCES KHOAHOC (CourseID);
ALTER TABLE ctdonhang
ADD CONSTRAINT fk_ct_dh FOREIGN KEY (donhangid) REFERENCES donhang (donhangid);

ALTER TABLE baihoc
ADD CONSTRAINT fk_bh_kh FOREIGN KEY (CourseID) REFERENCES KHOAHOC (CourseID);

INSERT INTO USERS VALUES
    ('vnlam','$2b$10$o5ZohDUYxZbThSFE1Xx8dOyQYh3AbsXMr9dp2u19gbPv9afv8AzXC','Võ Ngọc Lâm',0,'vongoclam157@gmail.com',false,false,'/img/lam.jpg'),
    ('bppkhanh','$2b$10$o5ZohDUYxZbThSFE1Xx8dOyQYh3AbsXMr9dp2u19gbPv9afv8AzXC','Bùi Phạm Phương Khanh',0,'meounu23@gmail.com',false,false,'/img/khanh.png'),
    ('nqd','$2b$10$o5ZohDUYxZbThSFE1Xx8dOyQYh3AbsXMr9dp2u19gbPv9afv8AzXC','Nguyễn Quang Duy',0,'nqduy98999@gmail.com',false,false,NULL),
    ('nvh','$2b$10$o5ZohDUYxZbThSFE1Xx8dOyQYh3AbsXMr9dp2u19gbPv9afv8AzXC','Nguyễn Văn Hiếu',0,'nguyenvanhieu9794@gmail.com',false,false,'/img/aaa.jpg'),
    ('trungokkt','$2b$10$o5ZohDUYxZbThSFE1Xx8dOyQYh3AbsXMr9dp2u19gbPv9afv8AzXC','Tran trung',0,'trungokkt1999@gmail.com',false,true,'/img/trungokkt.png');
	
INSERT INTO danhmuc VALUES
    (1,'Thiết kế đồ họa'),
    (2,'Nấu ăn'),
    (3,'Kinh doanh'),
    (4,'Lập trình'),
    (5,'Ngoại ngữ');
INSERT INTO GIAOVIEN VALUES
    ('T01','Virtus Learning Hub',NULL,'Photoshop','/img/T01.png'),
    ('T02','Daniel Walter Scott','Founder of http://bringyourownlaptop.com and http://instructorhq.com. Best selling course creator. Max Master at Adobe Max 2019!','Photoshop, Illustrator','/img/T02.png'),
    ('T03','Nastasia Peters','Nastasia Peters (aka Nas) is an Illustrator and Writer who recently moved from France to England. Her illustrations are a way to translate the imaginary worlds and characters that roam in her mind. She has been using vector for ten years and has published two fantasy novels in 2013. When she isn''t drawing or writing, she''ll be playing a game or tell her room mates she''s bored in hopes they''ll entertain her','Adobe After Effects, Photoshop, Illustrator,         Digital Painting','/img/T03.png'),
    ('T04','Gary Simon','Well, I''m a full stack developer with 2+ decades experience and I teach people how to design and code. I''ve created around 100+ courses for big brands like LinkedIn, Lynda.com, Pluralsight and Envato Network. Now, I focus all of my time and energy on this channel and my website Coursetro.com.Come to my discord server or add me on social media and say Hi!','Front end, UI/UX','/img/T04.png'),
    ('T05','Langforcus','Associate ProfessorSaint Petersburg State University','Language japanese','/img/T05.png'),
    ('T06','Gerry Landers','Education: M.A., Georgia State University. Gerry grew up in Atlanta. He graduated from the Paideia School in the Emory area. He attended Georgia State University where he majored in Spanish, with a minor in Psychology. Gerry studied in Mexico as an exchange student in high school and participated in two summer abroad programs in college, one in Costa Rica and the other in Japan. After undergraduate studies, he worked at the Atlanta airport for Japan Airlines for ten years. When that job ended, he went back to school at GSU for a master’s degree in Applied Linguistics. He has worked in education ever since. First, he was at Auburn University for five years. Then, he taught middle school for three years for Gwinnett County Public Schools. Afterwards, he spent a 1.5 year period at the University of South Alabama in Mobile, Alabama. Returning again to Atlanta, he taught for two private ESL schools before joining Georgia Institute of Technology. He loves swimming, cooking, seeing live music performances, and hanging out with friends and family.','Language english','/img/T06.png'),
    ('T07','YU Bin','YU Bin obtained Master Degree in Applied Linguistics from China Renmin University and has been teaching Chinese as a second language for about 20 years. She worked as Chinese teacher and Chinese supervisor for the University of Cambridge, as Chief Examiner for Cambridge Assessment, and teacher trainer for UCL IOE Confucius Institute. She published several books for Chinese GCSE and A-Level and was one of the writers of the Chinese textbook Jinbu. YU Bin is now a teacher of the School of Chinese as a Second Language, Peking University. She is very popular with her students with her knowledge, passion, kindness and humor.','Language chinese','/img/T07.png'),
    ('T08','Tamy Chapman','Ms. Tamy Chapman began teaching in the field of ESL in 1996 and since that time has taught all levels and subjects of ESL and teacher-training classes. Her teaching experience also includes high-school and community college in the U.S. and several years as an EFL teacher/teacher trainer with the Peace Corps in China. Her master’s degree in English is from Texas Tech University, and she has an ESL teaching certificate from UCI.','Language english','/img/T08.png'),
    ('T09','Carrie Anne Philbin','She is a teacher of computer science and an author. She is the Director of Education at the Raspberry Pi Foundation and is the Chair of the Computing At School (CAS) diversity and inclusion group, #CASInclude. She wrote the computing book Adventures in Raspberry Pi for teenagers. She runs the YouTube channel Geek Gurl Diaries and in 2017, was the host for Crash Course Computer Science.','Computer Science','/img/T09.jpg'),
    ('T10','Yasir Ghafoor','Software / SEO Expert','Adobe Illustrator','/img/T10.png'),
    ('T11','Uông Tòng Cáng','Netspace''s lecturer','Món Việt','/img/UTC.png'),
    ('T12','Nguyễn Kính Đức','Hướng Nghiệp Á Âu''s lecturer','Món Nhật Bản','/img/NKD.png'),
    ('T13','Trần Hồng Nhung','She had a Youtube chanel.She made a delicious food and view so good','Các loại bánh','/img/NhungTran.png'),
    ('T14','Maang Chi','She was born in Korea.She loves to cook & eat delicious food.She teaches Korean cooking on YouTube & her website & she wrote 2 bestselling books.','Món Hàn Quốc','/img/Maangchi.png'),
    ('T15','Ankur Aggarwal','Ankur Aggarwal has been in the online marketing space since 2010.','Marketing','/img/T15.png'),
    ('T16','Tim Stokes','Tim Stokes has built 7 businesses and mentored thousands of business owners for more than two decades. He specialises in fast Net Profit increases, cash flow solutions, systems, recruitment and strategic growth. His goal is to see his clients own their business, not feel owned or controlled by it, so they have an even increasing supply of cash in the bank, time off when they want and a business that grows faster and stress free.','Business','/img/T16.png');
	
INSERT INTO KHOAHOC VALUES
    ('C01','Become A Designer - Adobe Photoshop CC Course',59.99,'We introduce my new Adobe Photoshop design tutorial series, giving a run down of what you''ll learn and just how powerful Photoshop is to creative professionals.We''ll go over step by step how to use the software, create shapes, elements, modifying them and turm them into stunning graphics.If you want to start creating your first graphic designs or just brush up on your techniques then this is the course for you. ',19,'/img/C01.png','T01',1),
    ('C02','Adobe Illustrator CC - Essentials Training',30.99,'Hi there, my name is Dan. I''m an Adobe Certified Instructor, and an Adobe Certified Expert in Adobe Illustrator. Now together, me and you, are going to go through this course, and make beautiful art work together, using Illustrator. During this course, you won''t just learn how to use this tool, we''ll work through real world practical projects. Now this course is aimed at people completely new to Illustrator and maybe to Design, in general. We''re going to start absolutely right at the beginning and work our way through step by step. ',14,'/img/C02.png','T02',1),
    ('C03','Fundamentals of Digital Painting',19.99,'Want to learn how to create beautiful paintings using only a mouse, or tablet and stylus, and Adobe Photoshop?In this beginners'' course, digital artist Nastasia Peters will teach you the core fundamentals of digital painting, including all the tools you need to know, how to work with colors and textures, and how to create skin and facial features.If you''re ready to let your creativity loose onto a digital canvas, get started with The Fundamentals of Digital Painting.',17,'/img/C03.png','T03',1),
    ('C04','Adobe Photoshop CC 2020 Crash Course for Absolute Beginners',10,'Today, we''re stepping out of frontend dev & ui/ux and into the world of graphic design with this Adobe Photoshop CC 2020 Crash Course for Absolute NEWBIES! In this crash course, I assume no prior knowledge of Photoshop or graphic design in general, and we''re going to create a movie poster (technically for a music video) from scratch, using assets I''ve provided below!  The poster is for a real music video I''m releasing in a few days (12/9/2019), and in creating this poster, you''re going to learn Photoshop fundamentals. These fundamentals will take you a long way, so that you can create your own Photoshop projects.',1,'/img/C04.png','T04',1),
    ('C05','Advanced selections & masking in Adobe Photoshop - Select Anything! - Adobe Photoshop CC 2018',10,'Hi there, my name is  Dan and I am an Adobe Certified Instructor for Photoshop  - this is the Advanced Photoshop course.This course is not for people new to Photoshop. This is for people who already know the fundamentals. It is for people who have their own ways of doing things but believe there really is a better, faster way to work. What am I going to get from this course?You''ll learn the best selection and masking techniquesYou''ll know how to fix images that look ''hard to fix''You''ll master advanced levels and curves tricks, specifically with skin, adjusting and enhancing colorsYou''ll know how to convincingly remove all kinds of objects from imagesYou will become a type nerd. We''ll use font pairing in Typekit. We''ll also use Photoshop''s ability to guess fontsYou''ll learn to edit videos in Photoshop, who''d have thought?You''ll learn to master 3D in Photoshop!You''ll learn lots about professional, reusable mockups, techniques and shortcuts!Here''s some of the things we''ll be doing in this course:We will correct ''hard to fix'' images and learn what to do with blurry images. We will master Advanced Levels & Curves tricks and will work specifically with skin, adjusting and enhancing colours. We will learn how to convincingly remove all kinds of objects from images. My personal favourite section will show you how to distort, bend & reshape images.We will look at how current trending visual styles are easily created, duotones, glitches and orange/teal colour grading.There is a big section on advanced retouching techniques, advanced healing, advanced cloning & patching. You will learn how to edit videos in Photoshop. We will also animate static images creating parallax videos plus the very cool cinemagraphs sometimes called ''living pictures'' - great for social media. This course has a strong focus on workflow. We use real world, practical projects and show you the professional techniques and shortcuts which will save you hours using Photoshop. Throughout the course I have many class exercises for you to use in order to practice your skills. ',1,'/img/C05.png','T02',1),
    ('C06','Illustrator Advanced Training ',15.99,'Hi there, welcome to this Adobe Illustrator Advanced course. My name is Dan, and I''m an Adobe Certified Instructor, and Adobe Certified Expert in Illustrator. Now this is an advanced look at Illustrator. So it''s not for people who are brand new to the software. It''s for people who already understand the fundamentals. If you already know what an Anchor Point is, and how to adjust it then this is the course for you. Introduction to Advanced Adobe Illustrator CC - Illustrator Advanced Training Tutorial by Bring Your Own Laptop, get your free downloadable exercise files and printable PDF',18,'/img/C06.png','T02',1),
    ('C07','Improve Your English Communication Skills Specialization',20,'About this SpecializationThis Specialization helps you improve your professional communication in English for successful business interactions. Each course focuses on a particular area of communication in English: writing emails, speaking at meetings and interviews, giving presentations, and networking online. Whether you want to communicate to potential employers, employees, partners or clients, better English communication can help you achieve your language and professional goals. The Capstone course will focus especially on making those important connections to take your career or business to the next level. Make yourself more competitive by improving your English through this Specialization: Improve Your English Communication Skills.',4,'/img/C07.png','T06',5),
    ('C08','Japanese for beginners',40.99,'About this CourseJapanese language has become extremely popular among learners in recent years, since it is the best way to explore one of the richest and most mysterious cultures of the modern East. This course is  aimed at those who are interested in understanding Japanese way of thinking and view of the world through learning the language. Course materials are provided by the teaching staff from the Department of Japan Studies.Upon completion of this course the learners will be able: 1. To read simple texts in Japanese and write using the hiragana and katakana scripts as well as the kanji characters.2. To understand basic vocabulary in speech and use it in everyday communicative situations.3. To form their own sentences using the provided grammar material.The course provides extensive materials on Japanese grammar, phonetics, writing system and communication etiquette, as well as exercises for learners to apply the new knowledge. The vocabulary of the course consists of more than 200 words. Those who are interested in continuing their learning of Japanese language can proceed to the second part of this course - Japanese for beginners 2.',5,'/img/C08.png','T05',5),
    ('C09','Learn Chinese: HSK Test Preparation Specialization',10.99,'This specialization consists of three elementary language courses, aims to improve your Chinese language skills effectively and systematically. This specialization introduces everyday language and includes activities to practice all four language skill: conversation, comprehension, reading and writing. You will learn about Chinese culture and basic Chinese Characters more, will possess the ability to further your Chinese language studies.',3,'/img/C09.png','T07',5),
    ('C10','Tricky American English Pronunciation',50,'In this course, you’ll practice the sounds of American English that might sometimes be confusing. You''ll practice both consonant and vowel sounds. You’ll also learn about the things that give English its special “music,” such as how to stress the right syllable in a word, how to make your voice go up and down in a natural-sounding melody, and how to naturally connect sounds and words. Learning these things will help you speak more clearly and make sure that others can understand what you''re saying.',3,'/img/C10.png','T08',5),
    ('C11','Everything you need to know about business and startup basics',47,' Learn the foundation concepts underlying all businesses, small to large. a video tutorial that covers all the basics, explaining concepts such as business goals, stakeholders, profits, and various types of businesses. Outlines what you need to think about if you were to start your own business, such as determining what your product or service will be, making and delivering your product or service, and funding your business.',11,'/img/C11.png','T11',3),
    ('C12','Business Administration ',32,'This course is designed to help students understand what an Master of Business Administration (MBA) is from both a functional and educational standpoint, and the value of starting a business from an MBA perspective. Students will follow Erik, who would like to open a café, but doesn’t know where to begin. He consults Susan, who has an MBA degree and is able to help him along the way.',9,'/img/C12.png','T12',3),
    ('C13','Introduction to Digital Marketing | (FREE Digital Marketing Course)',10,'Ankur Aggarwal  helps you become a Pro Digital Marketer and make money online.',20,'/img/C13.png','T15',3),
    ('C14','The Mechanics of How Computers Work',23,'Carrie Anne Philbin teaches you computer science! This course is based on introductory college-level material as well as the AP Computer Science Principles guidelines. By the end of this course, you will be able to: *Outline the history of computers and the design decisions that gave us modern computers                                                                                                                        *Describe the basic elements of programming and software                                                                                      *Identify the basic components of computer hardware and what they do                                                                                                   *Describe how computers are used and how that has evolved over time                                                                *Appreciate how far computers have come and how far they might take us ',9,'/img/C14.jpg','T14',4),
    ('C15','The Basics of Programming and Software',10,'Carrie Anne Philbin teaches you computer science! This course is based on introductory college-level material as well as the AP Computer Science Principles guidelines. By the end of this course, you will be able to: *Outline the history of computers and the design decisions that gave us modern computers                                                                                                                        *Describe the basic elements of programming and software                                                                                      *Identify the basic components of computer hardware and what they do                                                                                                   *Describe how computers are used and how that has evolved over time                                                                *Appreciate how far computers have come and how far they might take us ',7,'/img/C15.jpg','T14',4),
    ('C16','Computer Hardware',10,'Carrie Anne Philbin teaches you computer science! This course is based on introductory college-level material as well as the AP Computer Science Principles guidelines. By the end of this course, you will be able to: *Outline the history of computers and the design decisions that gave us modern computers                                                                                                                        *Describe the basic elements of programming and software                                                                                      *Identify the basic components of computer hardware and what they do                                                                                                   *Describe how computers are used and how that has evolved over time                                                                *Appreciate how far computers have come and how far they might take us ',7,'/img/C16.jpg','T14',4),
    ('C17','The Rise of Personal Computers and Graphics',7,'Carrie Anne Philbin teaches you computer science! This course is based on introductory college-level material as well as the AP Computer Science Principles guidelines. By the end of this course, you will be able to: *Outline the history of computers and the design decisions that gave us modern computers                                                                                                                        *Describe the basic elements of programming and software                                                                                      *Identify the basic components of computer hardware and what they do                                                                                                   *Describe how computers are used and how that has evolved over time                                                                *Appreciate how far computers have come and how far they might take us ',4,'/img/C17.jpg','T14',4),
    ('C18','Artificial Intelligence',7,'Carrie Anne Philbin teaches you computer science! This course is based on introductory college-level material as well as the AP Computer Science Principles guidelines. By the end of this course, you will be able to: *Outline the history of computers and the design decisions that gave us modern computers                                                                                                                        *Describe the basic elements of programming and software                                                                                      *Identify the basic components of computer hardware and what they do                                                                                                   *Describe how computers are used and how that has evolved over time                                                                *Appreciate how far computers have come and how far they might take us ',4,'/img/C18.jpg','T14',4),
    ('C19','Adobe Illustrator CS6 - Logo Designing Course in Adobe Illustrator Cs6',8,'This class is extensive but is gentle and paced well enough for beginners to work through the course. There are both beginner and intermediate level topics discussed with some advanced topics discussed later on in the course.This will be for anyone interested in working through a course that has a deep focus on logo design or any designer who wants to fine tune their logo design and presentation skills.Who this course is for:Graphic Designers wanting to up their logo design skillsNewcomers or beginners to design or graphic design wanting to learn the logo design process and theory from start to finishThose looking to seek client work and wanting to know how to work with clientsIntermediate designs who want a fresh perspective on logo design theory and brainstormingThose wanting to explore Adobe Illustrators tools further for Logo DesignThose wanting a course that has a deep focus on logo design',7,'/img/C19.png','T10',1),
    ('C20','Adobe Illustrator CC 2017 for Web and UI Work',20.99,'UI design skills are one of the most employable opportunities of our lifetime. In this course you’ll learn how to design a professional website in Adobe Illustrator. We’ll start right at the basics of Illustrator and work our way through to building professional UI designs. This course doesn’t cover how to code a website but focuses on the design processes that professional UI designers use when working.',25,'/img/C20.png','T02',1),
    ('C21','Vietnamese''s Food',10,'When studying this course, you will learn Vietnamese food, of course, it will increase the flavor and enrich the daily meals.',8,'/img/monviet.png','T11',2),
    ('C22','Japanese''s Food',14.50,'These dishes are all famous Japanese dishes that we have to try at least once in our life.However, making them yourself may not be as delicious and flavorful as Japan.',6,'/img/monnhat.png','T12',2),
    ('C23','Korea''s Food',12.30,'These dishes are all popular Korean dishes, but it also makes Vietnamese people eat once, they will never forget it.',6,'/img/monhan.png','T14',2),
    ('C24','Cake',8.99,'The cakes come from many different countries. When we hear the name of the cake, we can know where this cake can start',5,'/img/monbanh.png','T13',2),
    ('C25','Business English Course',0,'This business English lesson looks at language for expressing opinions in English in both formal and informal business English situations.',3,'/img/C26.png','T01',3),
    ('C26','Business Courses Online',50,'Business and management training courses and entrepreneurship can be confusing for small business and company owners so this video was recorded for those people especially who want better business management skills.',10,'/img/C27.png','T16',3);
	
INSERT INTO BAIHOC VALUES
    ('S01',1,'Getting Started - Adobe Photoshop Design Tutorial Series','faifl6geUg8','C01'),
    ('S02',2,'Creating Our First Document - #2 Adobe Photoshop Design Tutorial Series','XMSj0lRausQ','C01'),
    ('S03',3,'Placing Images - #3 Adobe Photoshop Design Tutorial Series','uVL4C9IKEh8','C01'),
    ('S04',4,'Layers & Groups - #4 Adobe Photoshop Design Tutorial Series','1-s3CJKtbOg','C01'),
    ('S05',5,'Selection Tools - #5 Adobe Photoshop Design Tutorial Series','i0Guy26fKBA','C01'),
    ('S06',6,'Making Larger Selections - #6 Adobe Photoshop Design Tutorial Series','JoHX8k_5RRc','C01'),
    ('S07',7,'Using The Paint Brush Tool - #7 Adobe Photoshop Design Tutorial Series','p077VlV7Uxk','C01'),
    ('S08',8,'More Paint Tools - #8 Adobe Photoshop Design Tutorial Series','xUkqqWUFFbQ','C01'),
    ('S09',9,'Using Custom Brushes - #9 Adobe Photoshop Design Tutorial Series','40xYzn-Dxzk','C01'),
    ('S10',10,'Using Lines & Smart Guides - #10 Adobe Photoshop Design Tutorial Series','SH7bRTX7xHo','C01'),
    ('S11',11,'Working With Text Type & Fonts - #11 Adobe Photoshop Design Tutorial Series','DRpXzcqLAqI','C01'),
    ('S12',12,'Using Blending Options - #12 Adobe Photoshop Design Tutorial Series','PHK6KLv7Fb8','C01'),
    ('S13',13,'Bevel & Emboss Effect - #13 Adobe Photoshop Design Tutorial Series','sCJbcuxvQjw','C01'),
    ('S14',14,'Using Overlay Effects - #14 Adobe Photoshop Design Tutorial Series','YOOPW8rC9sc','C01'),
    ('S15',15,'Adjustment Layers - #15 Adobe Photoshop Design Tutorial Series','lZ1f5lkc9-g','C01'),
    ('S16',16,'Adjusting Light Levels - #16 Adobe Photoshop Design Tutorial Series','i-XPC7a0LF0','C01'),
    ('S17',17,'Color Adjustment Layers - #17 Adobe Photoshop Design Tutorial Series','Dwo2i6K1tVI','C01'),
    ('S18',18,'Using Layer Masks - #18 Adobe Photoshop Design Tutorial Series','Pksz4MHqlCY','C01'),
    ('S19',19,'Creating Complex Vector Shapes - #19 Adobe Photoshop Design Tutorial Series','qyUlhWVzZ8s','C01'),
    ('S20',1,'Introduction To Adobe Illustrator CC for beginners - Adobe Illustrator CC 2018','01yk4wsOFdQ','C02'),
    ('S21',2,'Getting Started with Illustrator & Exercise Files - Adobe Illustrator CC 2018','QvNB1fl4amE','C02'),
    ('S22',3,'How to draw in Illustrator with shapes & lines - Adobe Illustrator CC 2018','6iypq-8OeVY','C02'),
    ('S23',4,'How to draw using the Shape Builder tool - Adobe Illustrator CC 2018','uLQwiyil2bA','C02'),
    ('S24',5,'How to curve type around a badge using Illustrator - Adobe Illustrator CC 2018','5tbRUjmk0U4','C02'),
    ('S25',6,'How to make Gradients and Mask Images - Adobe Illustrator CC 2018','l0M2Zv958vA','C02'),
    ('S26',7,'How to use The Liquify Tool and Vectorise Images - Adobe Illustrator CC 2018','fJPtNx76MHU','C02'),
    ('S27',8,'Redrawing the Mastercard Logo - Adobe Illustrator CC 2018','ioySw8U4ivA','C02'),
    ('S28',9,'Redrawing the Instagram Logo - Adobe Illustrator CC 2018','kQjnuSNpujM','C02'),
    ('S29',10,'Redrawing the Kodak Logo - Adobe Illustrator CC 2018','BoAU6fkv0dg','C02'),
    ('S30',11,'Redrawing the eHarmony Logo - Adobe Illustrator CC 2018','814mf3I5K2A','C02'),
    ('S31',12,'Redrawing the Tinder Logo - Adobe Illustrator CC 2018','9ov8mTzRnPI','C02'),
    ('S32',13,'Redrawing the BP Logo - Adobe Illustrator CC 2018','_sb-6UhiP9A','C02'),
    ('S33',14,'Adobe Illustrator Cheat Sheet and Shortcuts - Adobe Illustrator CC 2018','Se2RDUlpx9Q','C02'),
    ('S34',1,'01 Introduction','Xef_D2HNAq8','C03'),
    ('S35',2,'02 Introduction to Adobe Photoshop','RKlHAK3F1Ro','C03'),
    ('S36',3,'03 Photoshop Tools and Shortcuts','FoJ97v8CZZI','C03'),
    ('S37',4,'04 How to Create Line Art','Q0c__CKDKgg','C03'),
    ('S38',5,'05 Painting in Grayscale: Rough Parts','GiSIGPxPE7g','C03'),
    ('S39',6,'06 Painting in Grayscale: Detail Work','nR9FmuhyVFY','C03'),
    ('S40',7,'07 Creating Our Base Colors','Xz5_IvfCeD4','C03'),
    ('S41',8,'08 Learn About Color Temperature','Jd3SXViIGX8','C03'),
    ('S42',9,'09 How to Make a Photoshop Brush','EPLgy7UC_qI','C03'),
    ('S43',10,'10 Skin and Facial Features','wgdqRZkjfU8','C03'),
    ('S44',11,'11 Hair','ugjQwy2wQDE','C03'),
    ('S45',12,'12 Fabric','ekb-ixCfkDc','C03'),
    ('S46',13,'13 Creating a Wood Effect','AuYxU__68cI','C03'),
    ('S47',14,'14 Creating a Metal Effect','igCvYSCdJiU','C03'),
    ('S48',15,'15 Final Touches','0FDTP-5A5lo','C03'),
    ('S49',16,'16 Background','vgWMqwrbQEE','C03'),
    ('S50',17,'17 Final Thoughts','o5k8Vxepf0Q','C03'),
    ('S51',1,'Adobe Photoshop CC 2020 Crash Course for Absolute Beginners','kfMn1SzXVAg','C04'),
    ('S52',1,'Advanced selections & masking in Adobe Photoshop - Select Anything! - Adobe Photoshop CC 2018','X-4IFMG-_nQ','C05'),
    ('S53',1,'Introduction to Advanced Adobe Illustrator CC','lFf9MbIyHhM','C06'),
    ('S54',2,'Advanced Pen Tool Tricks using Adobe Illustrator','E0CjYTAMaV0','C06'),
    ('S55',3,'The shape builder tool in Adobe Illustrator CC','fbN213k1U1Y','C06'),
    ('S56',4,'Advanced Keyboard Shortcuts for Illustrator CC','I2n3vMWv8uo','C06'),
    ('S57',5,'How to color a real hand drawing using Illustrator','jipchOap22g','C06'),
    ('S58',6,'How to Recolour your artwork in Adobe Illustrator ','Yuh4SamCokc','C06'),
    ('S59',7,'How to make long shadows in Adobe Illustrator','E4RY-ZDmcEI','C06'),
    ('S60',8,'How to make images Black & white & mix with color','4Rxc4_JLvZo','C06'),
    ('S61',9,'How to create a Duotone image effect ','nwXDZAJB8X8','C06'),
    ('S62',10,'How to put text type into the shape of a letter','qwawUIdPKDk','C06'),
    ('S63',11,'How to add a stroke around text or shapes','9H_aNw5mSjk','C06'),
    ('S64',12,'How to make Semi flat 3D icons & UI design','6sVksQ426Uc','C06'),
    ('S65',13,'How to make the paper cut effect in Illustrator','h80ePAxbdPg','C06'),
    ('S66',14,'How to distort bend shapes & type in Illustrator','KWelr9vWu34','C06'),
    ('S67',15,'How to make 3D gradient lettering blends in Illustrator ','nWSsepIcT3w','C06'),
    ('S68',16,'How to make a Linocut effect in Illustrator','UiNj9bbOKds','C06'),
    ('S69',17,'How to use Illustrator for Web & UI design','t5ZhbPBbhjI','C06'),
    ('S70',18,'What next after your Illustrator Advanced course','cZRMKDKsryw','C06'),
    ('S71',1,'Lesson 1: Introduction to Course','vIZE7-jbJEE','C07'),
    ('S72',2,'Lesson 2: Small Talk & Conversational Vocabulary','MFuT4U2izD0','C07'),
    ('S73',3,'Lesson 3: Key Pronunciation: Stress & Intonation','VSwY-Qmcjc0','C07'),
    ('S74',4,'Lesson 4: The Elevator Speech','LIuuozelnBA','C07'),
    ('S75',5,'Lesson 5: Basics of Meeting Online','DfwpE645ZMU','C07'),
    ('S76',6,'Lesson 6: Group Discussion Language','bkQQJhyeXMg','C07'),
    ('S77',7,'Lesson 7: Video Conference Role Play','TVwpZlHuMwY','C07'),
    ('S78',8,'Lesson 8: Let''s Learn Telephone Language','PqtM92vEr3Y','C07'),
    ('S79',9,'Lesson 9: Key Pronunciation - Can/Can''t&Numbers','o2c4MgwsqQw','C07'),
    ('S80',10,'Lesson 10: First Impressions: Body Language','gihhbcvTq6E','C07'),
    ('S81',1,'What''s the difference between "So Desu Ka" and "So Desu Ne"? - Japanese Grammar','JbSeNTqvXYc','C08'),
    ('S82',2,'How to Say Mother in Japanese - Haha vs Okaasan (母 vs お母さん)','5SRjA32X0uY','C08'),
    ('S83',3,'What is DAYO and How Do You Use it in Japanese?','c0s2EX1Ic-A','C08'),
    ('S84',4,'How to Use “Okagesama de” in Japanese','cn1TGnz0HBw','C08'),
    ('S85',5,'Differences between SHE (kanojo) and GIRLFRIEND (kanojo) in Japanese','OeKsMfTMJgU','C08'),
    ('S86',6,'How to Express Hope in Japanese - Basic Japanese Grammar','0lEV_lxMgW4','C08'),
    ('S87',7,'When to say “Gochisou sama”? Thanks for the food in Japanese','GKRCFV982Cw','C08'),
    ('S88',8,'How do you use ni tsuite? について (about) - Japanese Grammar','7UmEbAjBlH8','C08'),
    ('S89',1,'Use Measure Word Like a Native Chinese Speaker Part 1','5SUgdstCEPw','C09'),
    ('S90',2,'How to Use Measure Words like a Native Speaker -Part 2','za3N6iGlCzI','C09'),
    ('S91',3,'Use measure words like a native speaker part 3','bJGy5CmuckM','C09'),
    ('S92',4,'Easy and Fun Chinese- kuài 块（Measure Word Or RMB Unit）','0vRTDsSEUJQ','C09'),
    ('S93',1,'How To Pronounce the L Sound in American English Part 2 | The Dark L Sound','FUWVldKrTDs','C10'),
    ('S94',2,'How to Say the TH Sound | American English Pronunciation Lesson','BBSU6A-CRx0','C10'),
    ('S95',3,'American Accent Training | American T | Flap T','_3zbmyUu8-s','C10'),
    ('S96',4,'How to Pronounce the TH Sound after T, D, N','wTqcXDiabN4','C10'),
    ('S97',5,'How to Pronounce the L sound in American English Part 1 | The Light L Sound | L vs R','8itLuqssAgA','C10'),
    ('S98',6,'How to Pronounce the American R Sound: American R Part 1','3XRTN5gW4oU','C10'),
    ('S99',7,'How to Pronounce R After a Vowel Sound- Vocalic R: American R Part ','WMkrolnBMPg','C10'),
    ('S100',8,'American English Pronunciation: The X Sound','fQ0P8QsEP5g','C10'),
    ('S101',1,'Everything you need to know about business and startup basics','RFDaxPoGA6U','C11'),
    ('S102',2,'How to write a business plan? step by step guide + templates','ejTCwPfZ1LY','C11'),
    ('S103',3,'Understanding marketing basics, and fundamentals','A2t-yhFaUC0','C11'),
    ('S104',4,'How to write a marketing plan? step by step guide + templates','qYH0EqPqWfs','C11'),
    ('S105',5,'Understanding branding basics and fundamental','MeLimVJom_0','C11'),
    ('S106',6,'Accounting overview, basics, and best practices','YjkRSlTxsZM','C11'),
    ('S107',7,'Bookkeeping overview, basics, and best practices','9t0NE4O2aU4','C11'),
    ('S108',8,'Finance overview, basics, and best practices','hSQQgcEPrfQ','C11'),
    ('S109',9,'Personal finance basics, and fundamentals','LNi4cC-OfgI','C11'),
    ('S110',10,'Business finance definition, basics, and best practices','9JPCSD4rCok','C11'),
    ('S111',11,'Investing overview, basics, and best practices','IxFEtbNWrWk','C11'),
    ('S112',1,'Business Administration Part 1','CP4UWi3etWY','C12'),
    ('S113',2,'Business Administration Part 2','z9QCqqNjHVc','C12'),
    ('S114',3,'Business Administration Part 3','t-_a6dfV8SQ','C12'),
    ('S115',4,'Business Administration Part 4','0ryBXH5tkU4','C12'),
    ('S116',5,'Business Administration Part 5','_K_zzCRBtAM','C12'),
    ('S117',6,'Business Administration Part 6','RL52wJbCHl4','C12'),
    ('S118',7,'Business Administration Part 7','BoLYMYHUis8','C12'),
    ('S119',8,'Business Administration Part 8','PCNpA4CM_nQ','C12'),
    ('S120',9,'Business Administration Part 9','qB124rOHANY','C12'),
    ('S121',1,'Introduction to Digital Marketing | (FREE Digital Marketing Course)','wfOp0lsCXAY','C13'),
    ('S122',2,'Digital Marketing Modules','DqKFjgGvbnU','C13'),
    ('S123',3,'How to start a blog (Domain, Hosting , Wordpress Theme)','FgtB4fWIjRE','C13'),
    ('S124',4,'Set up your blog like a professional blogger','ZjVoShBahRg','C13'),
    ('S125',5,'Driving traffic to your Blog/Website (Various Channels)','ZCRNCNDm8MQ','C13'),
    ('S126',6,'What is SEO: What is On page SEO and how to write an article','N8DhIndTi6E','C13'),
    ('S127',7,'Off-page SEO – What are Backlinks? (My working strategies revealed)','QYrupSGZ3B8','C13'),
    ('S128',8,'Master the basics of Google Analytics and Google Webmaster','i8EgzE0QU6Y','C13'),
    ('S129',9,'Affiliate Marketing','SLE72I-2lv8','C13'),
    ('S130',10,'How to start Social media marketing','TzATuJefUkc','C13'),
    ('S131',11,'Instagram marketing step-by-step : How to get 10,000 followers in 30 days','7NHOzZyDqDw','C13'),
    ('S132',12,'Youtube Marketing explained in 13 minutes (Backed by data)','wc0PV2z_04o','C13'),
    ('S133',13,'Facebook Ads in 2019 : From Facebook Ads Beginner to EXPERT','x01Xv_Vqxw8','C13'),
    ('S134',14,'Google Adwords Fundamentals : How to create your first campaign','fVJ1QS2_K4c','C13'),
    ('S135',15,'Content Marketing: Hidden tactics and strategies','thpmu3i1-Kg','C13'),
    ('S136',16,'Email Marketing for beginners ($0 to $10,000/month)','IwayrUN9R4A','C13'),
    ('S137',17,'Landing page: How to Make a Beautiful landing page','Pk0USzDxfsg','C13'),
    ('S138',18,'ORM – What is online reputation management','rtWs2CJ6H90','C13'),
    ('S139',19,'Freelancing: How to make money as a freelancer','iWR3se1Y1UU','C13'),
    ('S140',20,'How to get Digital Marketing job?','um1KoEkjk6I','C13'),
    ('S141',1,'Early Computing: Crash Course Computer Science #1','O5nskjZ_GoI','C14'),
    ('S142',2,'Electronic Computing: Crash Course Computer Science #2','LN0ucKNX0hc','C14'),
    ('S143',3,'Boolean Logic & Logic Gates: Crash Course Computer Science #3','gI-qXk7XojA','C14'),
    ('S144',4,'Representing Numbers and Letters with Binary: Crash Course Computer Science #4','1GSjbWt0c9M','C14'),
    ('S145',5,'How Computers Calculate - the ALU: Crash Course Computer Science #5','1I5ZMmrOfnA','C14'),
    ('S146',6,'Registers and RAM: Crash Course Computer Science #6','fpnE6UAfbtU','C14'),
    ('S147',7,'The Central Processing Unit (CPU): Crash Course Computer Science #7','FZGugFqdr60','C14'),
    ('S148',8,'Instructions & Programs: Crash Course Computer Science #8','zltgXvg6r3k','C14'),
    ('S149',9,'Advanced CPU Designs: Crash Course Computer Science #9','rtAlC5J1U40','C14'),
    ('S150',1,'Early Programming: Crash Course Computer Science #10','nwDq4adJwzM','C15'),
    ('S151',2,'The First Programming Languages: Crash Course Computer Science #11','RU1u-js7db8','C15'),
    ('S152',3,'Programming Basics: Statements & Functions: Crash Course Computer Science #12','l26oaHV7D40','C15'),
    ('S153',4,'Intro to Algorithms: Crash Course Computer Science #13','rL8X2mlNHPM','C15'),
    ('S154',5,'Data Structures: Crash Course Computer Science #14','DuDz6B4cqVc','C15'),
    ('S155',6,'Alan Turing: Crash Course Computer Science #15','7TycxwFmdB0','C15'),
    ('S156',7,'Software Engineering: Crash Course Computer Science #16','O753uuutqH8','C15'),
    ('S157',1,'Integrated Circuits & Moore’s Law: Crash Course Computer Science #17','6-tKOHICqrI','C16'),
    ('S158',2,'Operating Systems: Crash Course Computer Science #18','26QPDBe-NB8','C16'),
    ('S159',3,'Memory & Storage: Crash Course Computer Science #19','TQCr9RV7twk','C16'),
    ('S160',4,'Files & File Systems: Crash Course Computer Science #20','KN8YgJnShPM','C16'),
    ('S161',5,'Compression: Crash Course Computer Science #21','OtDxDvCpPL4','C16'),
    ('S162',6,'Keyboards & Command Line Interfaces: Crash Course Computer Science #22','4RPtJ9UyHS0','C16'),
    ('S163',7,'Screens & 2D Graphics: Crash Course Computer Science #23','7Jr0SFMQ4Rs','C16'),
    ('S164',1,'The Cold War and Consumerism: Crash Course Computer Science #24','m8i38Yq1wX4','C17'),
    ('S165',2,'The Personal Computer Revolution: Crash Course Computer Science #25','M5BZou6C01w','C17'),
    ('S166',3,'Graphical User Interfaces: Crash Course Computer Science #26','XIGSJshYb90','C17'),
    ('S167',4,'3D Graphics: Crash Course Computer Science #27','TEAtmCYYKZA','C17'),
    ('S168',1,'Machine Learning & Artificial Intelligence: Crash Course Computer Science #34','z-EtmaFJieY','C18'),
    ('S169',2,'Computer Vision: Crash Course Computer Science #35','-4E2-0sxVUM','C18'),
    ('S170',3,'Natural Language Processing: Crash Course Computer Science #36','fOvTtapxa9c','C18'),
    ('S171',4,'Robots: Crash Course Computer Science #37','3XkL0qQ21Oo','C18'),
    ('S172',1,'Lecture # 1: Adobe illustrator Logo Design','uuAUdpriHb4','C19'),
    ('S173',2,'Lecture # 2: Adobe illustrator Logo Design','lNbTZvgExPI','C19'),
    ('S174',3,'Lecture # 3: Adobe illustrator Logo Design','hutIP3ECkl8','C19'),
    ('S175',4,'Lecture # 4: Adobe illustrator Logo Design','GNkpU01HFjk','C19'),
    ('S176',5,'Lecture # 5: Adobe illustrator Logo Design','aNiYghwKLTw','C19'),
    ('S177',6,'Lecture # 6 | How to make Cover TV Channel','rbiPkBDlRx0','C19'),
    ('S178',7,'Lesson # 7 Pathfinder Palette in Adobe Illustrator CS6 ','5MZ6SaI8A0I','C19'),
    ('S179',1,'Adobe Illustrator for Web and UI Work ','mnUJpDCajh0','C20'),
    ('S180',2,'Am I a UI UX designer now? ','uzl1AD4V0iM','C20'),
    ('S181',3,'Photoshop vs Illustrator vs Sketch vs InDesign vs Adobe XD ','6eQ50goMIQM','C20'),
    ('S182',4,'What is Illustrator’s role when designing a website ','OTRAYOsT_m0','C20'),
    ('S183',5,'Download the exercise files, completed files & cheat sheet','V7USJ7yGtn4','C20'),
    ('S184',6,'Workspace & Illustrator preferences ready for UI work','q3wgEIUVZr0','C20'),
    ('S185',7,'Sitemap vs Wireframe ','mizabdZIKZc','C20'),
    ('S186',8,'Creating a sitemap in Illustrator','tSzvEYPvTfk','C20'),
    ('S187',9,'What screen sizes to use for responsive web design','Sq6Cm4aTHQA','C20'),
    ('S188',10,'What is a grid system & responsive mobile & tablet design','5ujOvh7SIXY','C20'),
    ('S189',11,'How to make a responsive 12 column grid in Illustrator','ow3Z_ULM0cA','C20'),
    ('S190',12,'Creating a wireframe - Low fidelity - hand drawn','ReiUKI9nUiU','C20'),
    ('S191',13,'Creating a wireframe - High Fidelity','KiXzz9tXIho','C20'),
    ('S192',14,'Creating the Tablet and Mobile wireframes in Illustrator','y6490yDWKHU','C20'),
    ('S193',15,'Inspiration for your web design','fyoTVRk0egE','C20'),
    ('S194',16,'Starting your web design using Illustrator templates','LiXZ9hf0mQw','C20'),
    ('S195',17,'Bring in your vector logo to the layout ','d6mMPHjGkoQ','C20'),
    ('S196',18,'Color.Adobe.com','nP2Y0MRgJY0','C20'),
    ('S197',19,'Matching brand colors using Adobe Illustrator','Y2oKJhvDO80','C20'),
    ('S198',20,'Using the right web fonts Google Fonts & Typekit ','VBg8DzMppKM','C20'),
    ('S199',21,'Production video - finalizing nav, hero box and fonts','R-sTxML4U3E','C20'),
    ('S200',22,'How to adjust vector shapes in Illustrator ','8USfw_2IELg','C20'),
    ('S201',23,'Export your full page web UI mockups from Illustrator 2017','FyhwY6WHoNE','C20'),
    ('S202',24,'Should I be using SVG export','g_omLTD3DEc','C20'),
    ('S203',25,'Cheat sheet','n9DsttORehk','C20'),
    ('S204',1,'Cách nấu Mì Vịt Tiềm','vLBoSX8L4rY','C21'),
    ('S205',2,'Cách làm Mì Xào Xá Xíu','EMSBFej0Guk','C21'),
    ('S206',3,'Cách làm Gỏi Đu Đủ Ba Khía','D_4baTUcuCk','C21'),
    ('S207',4,'Cách làm Há Cảo','eAgzGRe7rV8','C21'),
    ('S208',5,'Cách làm Cơm Hấp Lá Sen','R1mizT-8oTw','C21'),
    ('S209',6,'Cách làm chân giò hầm thuốc bắc','NMMBnFEMm_I','C21'),
    ('S210',7,'Cách làm cơm chiên ngọc bích','wFsThuKfimQ','C21'),
    ('S211',1,'Cách làm Sukiyaki','cWuPbIm3B24','C22'),
    ('S212',2,'Cách nấu Mì Ramen','v1gXjJvsPzM','C22'),
    ('S213',3,'Cách làm bánh xèo Nhật Bản Okonomiyaki','TexyxAzTeuE','C22'),
    ('S214',4,'Cách làm TONKATSU','aUUZcB4eWWE','C22'),
    ('S215',5,'Cách làm Sashimi Cá Hồi và Sashimi Cá Ngừ Đại Dương','jyq7V6sJiW0','C22'),
    ('S216',6,'Cách làm mì Soba thủ công','b41cZXEI7GY','C22'),
    ('S217',1,'Cách Làm Đậu Phụ Om Cay Kiểu Hàn Quốc','Fwtwl1AsTzU','C23'),
    ('S218',2,'Cách làm miếng Hàn Quốc','2WxpAQeDohk','C23'),
    ('S219',3,'Cách làm mì tương đen Hàn Quốc','XUrIuI3ZJPA','C23'),
    ('S220',4,'Cách làm bánh kếp hải sản','Z8JLfr2s3DQ','C23'),
    ('S221',5,'Hướng Dẫn Làm Cơm Trộn Hàn Quốc (Bibimbap)','J730p50xtu4','C23'),
    ('S222',6,'Cách làm Thịt xào cay','LzSqqDych00','C23'),
    ('S223',1,'Cách làm Pizza Viền Phô mai','I1yKe_JT3pU','C24'),
    ('S224',2,'Cách làm bánh mì sữa Hokkaido','ta6ViUlx-CE','C24'),
    ('S225',3,'Cách làm Bánh mì phô mai bơ tỏi','xX_iXdyhavc','C24'),
    ('S226',4,'Cách làm bánh bông lan DAS-Keto-Lowcarb','AmaDwvuc_to','C24'),
    ('S227',5,'Cách làm Bánh rán Đô-Rê-Mon ','OfzfsHW_ABs','C24'),
    ('S228',1,'Business English for Meetings','e7n2K5gR-rk','C25'),
    ('S229',2,'Making Suggestions in English','lfEBjdzp4jw','C25'),
    ('S230',3,'Responding to Suggestions in English','jCYLhRKMk8A','C25'),
    ('S231',1,'Business and Management Profit Tips','RMa1QLeJXpI','C26'),
    ('S232',2,'How to Manage a Business','XZRN3GJ5Vx0','C26'),
    ('S233',3,'Types of Marketing Strategies','LhDPc_mZ6BA','C26'),
    ('S234',4,'How to Increase Profits','-5UxqGCmDGs','C26'),
    ('S235',5,'Increasing Sales by Referrals','3oBMt8bD0Wo','C26'),
    ('S236',6,'Business Development Strategies','gkYi3uexDG0','C26'),
    ('S237',7,'Business Marketing Strategies','SsTSxpujW9o','C26'),
    ('S238',8,'Sales & Marketing Strategies','tf_KpDWg5e4','C26'),
    ('S239',9,'Using Guarantees to Increase Sales','ZX6XAYAgQmA','C26'),
    ('S240',10,'Unique Phone Selling Techniques','oJnJBo31ld8','C26');
INSERT INTO danhgia VALUES
    ('DG01','Great',4,'2020-05-31 00:00:00','vnlam','C14'),
    ('DG02','No idea',3,'2020-05-30 00:00:00','vnlam','C17'),
    ('DG03','Hay',5,'2020-05-12 00:00:00','bppkhanh','C01'),
    ('DG04','Khong thich',2,'2020-05-10 00:00:00','bppkhanh','C05'),
    ('DG05','it''s ok',4,'2020-05-10 00:00:00','nqd','C11'),
    ('DG06','not very bad',3,'2020-05-31 00:00:00','nqd','C12'),
    ('DG07','The course is very good.',4,'2020-05-31 00:00:00','nvh','C20'),
    ('DG08','This course had a teacher who talked so fast.I couldn''t understand content of course',2,'2020-05-01 00:00:00','nvh','C06'),
    ('DG09','ok',4,'2020-05-29 00:00:00','trungokkt','C07'),
    ('DG10','tam on',5,'2020-05-29 00:00:00','trungokkt','C08');
INSERT INTO courseofuser VALUES
    ('COU01',2,'C14','vnlam'),
    ('COU02',1,'C17','vnlam'),
    ('COU03',5,'C01','bppkhanh'),
    ('COU04',0,'C05','bppkhanh'),
    ('COU05',2,'C11','nqd'),
    ('COU06',1,'C12','nqd'),
    ('COU07',15,'C20','nvh'),
    ('COU08',8,'C06','nvh'),
    ('COU09',0,'C07','trungokkt'),
    ('COU10',0,'C08','trungokkt');
INSERT INTO donhang VALUES
    ('DH01',23,'Momo','2020-05-30 00:00:00','vnlam'),
    ('DH02',7,'Momo','2020-05-30 00:00:00','vnlam'),
    ('DH03',59.99,'Paypal','2020-04-15 00:00:00','bppkhanh'),
    ('DH04',10,'Paypal','2020-04-20 00:00:00','bppkhanh'),
    ('DH05',47,'Paypal','2020-05-31 00:00:00','nqd'),
    ('DH06',32,'Paypal','2020-05-31 00:00:00','nqd'),
    ('DH07',20.99,'Momo','2020-04-28 00:00:00','nvh'),
    ('DH08',15.99,'Momo','2020-04-20 00:00:00','nvh'),
    ('DH09',20,'Paypal','2020-03-12 00:00:00','trungokkt'),
    ('DH10',4099,'Paypal','2020-03-13 00:00:00','trungokkt');
INSERT INTO ctdonhang VALUES
    ('CDH01','DH01',23,'C14'),
    ('CDH02','DH02',7,'C17'),
    ('CDH03','DH03',59.99,'C01'),
    ('CDH04','DH04',10,'C05'),
    ('CDH05','DH05',47,'C11'),
    ('CDH06','DH06',32,'C12'),
    ('CDH07','DH07',20.99,'C20'),
    ('CDH08','DH08',15.99,'C06'),
    ('CDH09','DH09',20,'C07'),
    ('CDH10','DH10',4099,'C08');
